spring.application.name=imageFiles

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/saving_image_in_db
spring.jpa.hibernate.ddl-auto=update


server.port=8081